config/routes.rb
QRPay::Application.routes.draw do

  match '/payments/payment', :to => 'payments#payment', :as => 'paymentspayment', :via => [:get]

  match '/payments/relay_response', :to => 'payments#relay_response', :as => 'payments_relay_response', :via => [:post]

  match '/payments/receipt', :to => 'payments#receipt', :as => 'payments_receipt', :via => [:get]
  match 'qr/:num', :to => 'user#qr'

  resources :transactions

  resources :payment_infos

  match 'login_form' => 'user#login_form'
  match 'login' => 'user#login', :via => [:post]
  match 'signup_p' => 'user#create', :via => [:post]
  match 'signup' => 'user#signup'
  match 'download' => 'welcome#download'
  match 'pay' => 'transactions#phonePay', :via => [:post]
  match 'team' => 'welcome#team'
  resources :user, :only => [:show, :create]
  root :to => 'welcome#index'

  match 'logout' => 'user#logout'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RabbitQR | Mobile Payments</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-20351006-3']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
</head>
<body>
<div id="header">
	<a href="/" id="logo"></a>
	<div id="nav">
		<ul>
      <% if @user %>
        <li><%= link_to "Dashboard", user_path(@user.id) %> </li>
        <li><%= link_to "New Card", new_payment_info_path %></li>
        <% unless @user.payment_infos.blank? %>
          <li><%= link_to "Profile", edit_payment_info_path(@user.payment_infos[0].object_id) %></li>
        <% end %>
        <li><%= link_to "Logout", logout_path %></li>
      <% else %>
				<li><a href="http://blog.rabbitqr.com">Blog</a></li>
				<li><a href="/download/">Download</a></li>
				<li><a href="/team">Team</a></li>
				<li><%= link_to "Login", login_form_path %></li>
      <% end %>
		</ul>
	</div>

</div>

<%= yield %>
  <div id="footer">
      A <a href="http://startupbus.com">StartupBus 2011</a> creation.
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      <a href="http://blog.rabbitqr.com">Blog</a>
  </div>

</body>
</html>

app/views/layouts/authorize_net.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Direct Post Sample App</title>
    <style>
    body {
      text-align: center;
      font-family: Helvetica;
    }
    label {
      display: block;
    }
    </style>
  </head>
  <body>
    <%= yield %>
  </body>
</html>